#!/bin/python3

import sys

t = int(input().strip())

# Equation definition
def eq(x):
    return x * (x + 1)

for a0 in range(t):
    n = int(input().strip())
    
    n -= 1
    
    # Initialise variables
    mult3 = int(n/3)
    mult5 = int(n/5)
    mult15 = int (n/15)
    multSum = 0

    # Calculate final sum
    multSum =int(int(3 * eq(mult3) + 5 * eq(mult5) - 15 * eq(mult15)) // 2)

    print (multSum)
