#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    
    i = 0
    multSum = 0

    while i < n:
        if i%3 == 0 or i%5 == 0:
            multSum += i
        i += 1
    print (multSum)
